<?php

/**
 * PartidoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PartidoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PartidoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Partido');
    }
}