<?php

/**
 * VereadorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VereadorTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VereadorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Vereador');
    }
}