<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Partido', 'doctrine');

/**
 * BasePartido
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nome
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property Doctrine_Collection $Vereador
 * 
 * @method integer             getId()         Returns the current record's "id" value
 * @method string              getNome()       Returns the current record's "nome" value
 * @method timestamp           getCreatedAt()  Returns the current record's "created_at" value
 * @method timestamp           getUpdatedAt()  Returns the current record's "updated_at" value
 * @method Doctrine_Collection getVereador()   Returns the current record's "Vereador" collection
 * @method Partido             setId()         Sets the current record's "id" value
 * @method Partido             setNome()       Sets the current record's "nome" value
 * @method Partido             setCreatedAt()  Sets the current record's "created_at" value
 * @method Partido             setUpdatedAt()  Sets the current record's "updated_at" value
 * @method Partido             setVereador()   Sets the current record's "Vereador" collection
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePartido extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('partido');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'partido_id',
             'length' => 8,
             ));
        $this->hasColumn('nome', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Vereador', array(
             'local' => 'id',
             'foreign' => 'partido_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}