<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Vereador', 'doctrine');

/**
 * BaseVereador
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nome
 * @property string $telefone
 * @property string $email
 * @property integer $numero_votos
 * @property integer $partido_id
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property Partido $Partido
 * 
 * @method integer   getId()           Returns the current record's "id" value
 * @method string    getNome()         Returns the current record's "nome" value
 * @method string    getTelefone()     Returns the current record's "telefone" value
 * @method string    getEmail()        Returns the current record's "email" value
 * @method integer   getNumeroVotos()  Returns the current record's "numero_votos" value
 * @method integer   getPartidoId()    Returns the current record's "partido_id" value
 * @method timestamp getCreatedAt()    Returns the current record's "created_at" value
 * @method timestamp getUpdatedAt()    Returns the current record's "updated_at" value
 * @method Partido   getPartido()      Returns the current record's "Partido" value
 * @method Vereador  setId()           Sets the current record's "id" value
 * @method Vereador  setNome()         Sets the current record's "nome" value
 * @method Vereador  setTelefone()     Sets the current record's "telefone" value
 * @method Vereador  setEmail()        Sets the current record's "email" value
 * @method Vereador  setNumeroVotos()  Sets the current record's "numero_votos" value
 * @method Vereador  setPartidoId()    Sets the current record's "partido_id" value
 * @method Vereador  setCreatedAt()    Sets the current record's "created_at" value
 * @method Vereador  setUpdatedAt()    Sets the current record's "updated_at" value
 * @method Vereador  setPartido()      Sets the current record's "Partido" value
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVereador extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('vereador');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'vereador_id',
             'length' => 8,
             ));
        $this->hasColumn('nome', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('telefone', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('email', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('numero_votos', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('partido_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Partido', array(
             'local' => 'partido_id',
             'foreign' => 'id'));
    }
}