<?php
// auto-generated by sfAutoloadConfigHandler
// date: 2025/04/30 11:44:26
return array(

  // project

  // project_model

  // application
  'myuser' => '/home/gabrielsuptitz/Documents/Treinos_Testes/php-rest/parlavox_test/apps/frontend/lib/myUser.class.php',

  // modules
);
